<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" href="styles/vrc_default.css" />
		<link rel="shortcut icon" href="images/favicon.ico" />
		<!--[if IE]><link rel="stylesheet" type="text/css" href="http://www.rentalcodes.org/styles/vrc_ie.css" /><![endif]-->
		<script type="text/javascript" src="includes/javascript/jquery-plus-jquery-ui.js"></script>
		<!--<script type="text/javascript" src="http://www.rentalcodes.org/includes/javascript/ixedit/ixedit.packed.js"></script> 
		<link type="text/css" href="http://www.rentalcodes.org/includes/javascript/ixedit/ixedit.css" rel="stylesheet" />-->
		<meta name="description" content="A one-stop resource for information about Vermont's rental housing codes" />
		<title>Vermont Rental Housing Codes &#8212; A housing resource for Vermont town officials, landlords and tenants</title>
		<script type="text/javascript">
			$(document).ready(function() {
				if(!document.getElementById) return false;	//	Quit if browser doesn't support DOM scripting
				var sanitationDetails = document.getElementById("sanitationDetails");
				var buildingDetails = document.getElementById("buildingDetails");
				var structuralDetails = document.getElementById("structuralDetails");
				var leadDetails = document.getElementById("leadDetails");
				var leadDetails = document.getElementById("leadDetails");
				var lifeDetails = document.getElementById("lifeDetails");
				var mhDetails = document.getElementById("mobileHomeDetails");
				var otherConcernsDetails = document.getElementById("otherConcernsDetails");
				
				sanitationDetails.style.display = "none";
				buildingDetails.style.display = "none";
				structuralDetails.style.display = "none";
				leadDetails.style.display = "none";
				lifeDetails.style.display = "none";
				mhDetails.style.display = "none";
				otherConcernsDetails.style.display = "none";

			});
			/* ------ Code generated by IxEdit (ixedit.com). ------ */
			if(window.ixedit){ixedit.deployed = true};
			if(window.jQuery){jQuery(function(){
				(function(){ jQuery('a#sanitationLink').bind('mouseover', function(event, ui){var target = jQuery('p#sanitationDetails'); target.css('display','block'); var target = jQuery('p#detailsHole'); target.css('display','none')});})();
				(function(){ jQuery('a#sanitationLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#sanitationDetails'); target.css('display','none')});})();
				(function(){ jQuery('a#buildingLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#buildingDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#buildingLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#buildingDetails'); target.css('display','none')});})();
				(function(){ jQuery('a#structuralLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#structuralDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#structuralLink').bind('mouseout', function(event, ui){var target = jQuery('p#structuralDetails'); target.css('display','none'); var target = jQuery('p#detailsHole'); target.css('display','block')});})();
				(function(){ jQuery('a#leadLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#leadDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#leadLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#leadDetails'); target.css('display','none')});})();
				(function(){ jQuery('a#lifeLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#lifeDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#lifeLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#lifeDetails'); target.css('display','none')});})();
				(function(){ jQuery('a#mobileHomeLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#mobileHomeDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#mobileHomeLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#mobileHomeDetails'); target.css('display','none')});})();
				(function(){ jQuery('a#otherConcernsLink').bind('mouseover', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','none'); var target = jQuery('p#otherConcernsDetails'); target.css('display','block')});})();
				(function(){ jQuery('a#otherConcernsLink').bind('mouseout', function(event, ui){var target = jQuery('p#detailsHole'); target.css('display','block'); var target = jQuery('p#otherConcernsDetails'); target.css('display','none')});})();
			})};
		</script>
	</head>
	<body id="homeBody">
		<div class="container_12">
			<!--<div id="gridded">
			</div>-->
			
			<div id="header">
				<p id="logo"><a href="index.php"><span></span>Vermont Rental Codes</a></p>
				<p><em><span></span>A housing resource for Vermont town officials, landlords and tenants</em></p>
				<ul id="primaryMenu">
					<li class="hidden"><a href="index.php#content">Jump to content</a></li>
					<li><a href="who-are-you" id="faqLink" class="first">Who are you?</a>
						<ul id="faqSubLink">
							<li><a href="who-are-you/municipalities">Municipalities</a></li>
							<li><a href="who-are-you/landlords">Landlords</a></li>
							<li><a href="who-are-you/tenants">Tenants</a></li>
						</ul>
					</li>
					<li><a href="areas-of-interest/index.html" id="areasOfInterestLink">Areas of interest</a>
						<ul id="areasOfInterestSubLink">
							<li><a href="areas-of-interest/sanitation-facilities">Sanitation facilities</a></li>
							<li><a href="areas-of-interest/building-systems">Building systems</a></li>
							<li><a href="areas-of-interest/structural-elements">Structural elements</a></li>
							<li><a href="areas-of-interest/lead-paint">Lead paint</a></li>
							<li><a href="areas-of-interest/life-safety">Life safety</a></li>
							<li><a href="areas-of-interest/mobile-homes">Mobile homes</a></li>
							<li><a href="areas-of-interest/other-concerns">Other health and safety concerns</a></li>
						</ul>
					</li>
					<li><a href="resources/index.html" id="resourcesLink">Resources</a>
						<ul id="resourcesSubLink">
							<li><a href="resources/communities-with-local-codes.php">Communities with local codes</a></li>
							<li><a href="resources/town-health-officials.php">Directory of town health officials</a></li>
							<li><a href="resources/general-resources.php">General resources</a></li>
						</ul>
					</li>
					<li><a href="about-this-site.php" id="aboutThisSiteLink">About this site</a></li>
					<li><a href="news/index.php" id="blogLink">News</a></li>
				</ul>
				<ul id="secondaryMenu">
					<li><a id="homeLink" class="first" href="index.php">Home</a></li>
					<li><a id="searchLink" href="search.php">Search</a></li>
					<!--<li><a id="mailingListLink" href="http://www.rentalcodes.org/mailing-list.php">Mailing list</a></li>-->
					<li><a id="aboutUsLink" href="about-us.php">About us</a></li>
					<li><a id="contactLink" href="contact.php">Contact</a></li>
				</ul>
			</div>	<!-- END #header -->			
			<div id="content">
				<div class="grid_6">
					<h1 id="whoAreYou"><span></span>Who are you?</h1>
					<p><strong>Not sure</strong> what you're looking for? Tell us who you are:</p>
					<div class="whoButton">
						<a href="who-are-you/municipalities"><strong>Municipalities</strong><br />[Officials and town health officers]</a>
					</div>
					<div class="whoButton">
						<a href="who-are-you/landlords"><strong>Landlords</strong><br />[Property owners]</a>
					</div>
					<div class="whoButton">
						<a href="who-are-you/tenants"><strong>Tenants</strong><br />[Residents]</a>
					</div>
				</div>
				<div class="grid_6"><h1 id="areasOfInterest"><span></span>Areas of interest</h1>
						<p>Looking for answers within a <strong>specific topic</strong>? Pick it:</p>
						<div style="position:relative;">
							<div class="areasButton">
								<a id="sanitationLink" href="areas-of-interest/sanitation-facilities"><strong>Sanitation facilities</strong></a>
							</div>
							<p id="sanitationDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Sanitation facilities</strong><br />Matters concerning kitchen facilities, bathroom facilities, water supply, hot water, sewage disposal, trash, rodents and insects. (More ...)</p>
							
							<div class="areasButton">
								<a id="buildingLink" href="areas-of-interest/building-systems"><strong>Building systems</strong></a>
							</div>
							<p id="buildingDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Building systems</strong><br />Matters concerning heating, ventilation, electricity and lighting. (More ...)</p>
							
							<div class="areasButton">
								<a id="structuralLink" href="areas-of-interest/structural-elements"><strong>Structural elements</strong></a>
							</div>
							<p id="structuralDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Structural elements</strong><br />Vermont law specifies rental units need to be weather tight, watertight, rodent proof and in good repair. (More ...)</p>
							
							<div class="areasButton">
								<a id="leadLink" href="areas-of-interest/lead-paint"><strong>Lead paint</strong></a>
							</div>
							<p id="leadDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Lead paint</strong><br />Rules regarding essential maintenance practices (EMPs) and permitting for renovations of pre-1978 rental units. (More ...)</p>
							
							<div class="areasButton">
								<a id="lifeLink" href="areas-of-interest/life-safety"><strong>Life safety</strong></a>
							</div>
							<p id="lifeDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Life safety</strong><br />Rules regarding smoke and carbon monoxide (CO) detectors, exits and ventilation of fuel-burning heating appliances. (More ...)</p>
							
							<div class="areasButton">
								<a id="mobileHomeLink" href="areas-of-interest/mobile-homes"><strong>Mobile homes</strong></a>
							</div>
							<p id="mobileHomeDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Mobile homes/rented lots</strong><br />Vermont law specifies every rented mobile home lot must provide connection to electrical services, water supply and sewage disposal. (More ...)</p>
							
							<div class="areasButton">
								<a id="otherConcernsLink" href="areas-of-interest/other-concerns"><strong>Other health and<br />safety concerns</strong></a>
							</div>
							<p id="otherConcernsDetails"><img src="images/pointer.gif" height="28" width="23" alt=""/><strong>Other health and safety concerns</strong><br />Other matters outside Vermont's Health and Safety codes for residential rental housing. (More ...)</p>
														
							<p id="detailsHole">&nbsp;</p>
						</div>			
				</div>
			</div>	<!-- END #content -->
			
						<div id="footer">
				<ul>
					<li><a id="accessibilityLink" href="accessibility.php">Accessibility</a></li>
					<li><a id="legalLink" href="legal.php">Legal</a></li>
				</ul>
								<p>&copy;2011-18 Vermont Rental Codes. All rights reserved.<br />
				<a href="http://www.twitter.com/vtrentalcodes">Follow on Twitter</a></p>
			</div>	<!-- END #footer -->
			
			<script type="text/javascript">
			  var _gaq = _gaq || [];
			  _gaq.push(['_setAccount', 'UA-20538059-1']);
			  _gaq.push(['_trackPageview']);
			
			  (function() {
			    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			  })();
			</script>			
		</div>	<!--  END .container_12 -->
	</body>
</html>
